notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/4f71b9fa80e108068016
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always
dist: trusty
cache:
  directories:
  - $HOME/.opam
  - $HOME/build/pirapira/cpp-ethereum
sudo: required
before_install:
- BAMBOO=`pwd`
- sudo apt-get -qq update
- sudo apt-get install aspcud
# - git clone https://github.com/polyml/polyml.git
# - cd polyml
# - git checkout v5.6
# - ./configure
# - make
# - make compiler
# - sudo make install
# - cd -
# - sudo updatedb
# - locate libpolymain.a
- wget https://raw.github.com/ocaml/opam/master/shell/opam_installer.sh -O - | sudo sh -s /usr/local/bin
- export OPAMJOBS=2
- opam init -y --comp=4.02.3
- eval `opam config env`
- opam update
- opam upgrade -y
- opam install -y ocamlfind menhir batteries rope zarith ppx_deriving rpc
- git clone https://github.com/xavierleroy/cryptokit.git cryptokit
- cd cryptokit
- ocaml setup.ml -configure
- ocaml setup.ml -build
- ocaml setup.ml -install || echo "It fails the second time.  It's ok."
- cd ../..
- if [ ! -d cpp-ethereum/.git ]; then rm -rf cpp-ethereum; git clone https://github.com/ethereum/cpp-ethereum --recursive; fi
- sudo apt install -y build-essential libgmp-dev libleveldb-dev libmicrohttpd-dev
- sudo apt purge -y cmake
- wget https://cmake.org/files/v3.8/cmake-3.8.2-Linux-x86_64.tar.gz
- tar xf cmake-3.8.2-Linux-x86_64.tar.gz
- PATH=`pwd`/cmake-3.8.2-Linux-x86_64/bin:$PATH
- cmake --version
- cd cpp-ethereum
- git pull
- git submodule update --recursive
- mkdir -p build
- cd build
- cmake ..
- make -j3 eth
- sudo make install
- cd $BAMBOO
script:
- make
- make test
- make end-to-end
- which eth
- eth --version
- mkdir -p /tmp/test
- eth --test -d /tmp/test &> eth.log &
- until grep JSONRPC eth.log; do sleep 1; echo "waiting for eth"; done
- ./end-to-end.native
- PID=$!
- kill $PID
- cat eth.log
